packages/docs/src/pages/components/button.js
packages/docs/src/pages/components/card.js
packages/docs/src/pages/components/form.js
packages/docs/src/pages/components/paragraph.js
packages/docs/src/pages/components/text.js

Just a small set of corrections to the docs.
Totally in love with `react-ui`, keep up with it!

Small fixes to the docs

---

packages/docs/src/pages/components/stat.js
packages/docs/src/pages/index.js
packages/react-ui/index.js
packages/react-ui/src/components/stat/index.js

Add Stat component (#4)

---

CONTRIBUTING.md
packages/docs/src/pages/ecosystem/stats.js

Adding a contributing guide. Fixes https://github.com/siddharthkp/react-ui/issues/9 and https://github.com/siddharthkp/react-ui/issues/22
Will continue to add and improve with feedback

Contributing.md

---

packages/react-ui/src/themes/base.js
packages/react-ui/src/themes/dark.js
packages/react-ui/src/themes/light.js

add overflow to Card, border to MenuList

Theme fixes: 

---

packages/react-ui/src/components/stack/index.js
packages/react-ui/src/primitives/interpolate.js

fixes https://github.com/siddharthkp/react-ui/issues/20

Add support for RTL layouts in <Stack/> by using logical margin

---

packages/docs/src/components/example.js

Fix scrollbar bug in example.js

---

packages/docs/src/pages/components/theme-provider.js
packages/docs/src/pages/core-concepts/customising-tokens.js
packages/docs/src/pages/core-concepts/ideas.js
packages/docs/src/pages/getting-started/customisation.js

fix(docs): Fixed links to theme files

---

packages/docs/src/pages/components/text.js
packages/react-ui/package.json
yarn.lock

Adds docs for undocumented feature :)

Docs: Add size docs for Text

---

packages/docs/src/components/list.js
packages/docs/src/pages/changelog/index.js
packages/react-ui/src/components/stack/index.js

Gets published here: https://react-ui.dev/changelog#1.0.0-beta.25

Add changelog for beta.25

---

packages/react-ui/package.json
yarn.lock

Dependency @reach/menu-button is upgraded.
Reference to this issue #58

Upgraded @reach/menu-button

---

packages/docs/src/pages/components/dialog.js
packages/react-ui/src/themes/base.js
packages/react-ui/src/themes/dark.js
packages/react-ui/src/themes/light.js

Tweak designs for modal a bit

---

packages/docs/package.json
packages/docs/src/pages/core-concepts/index.js
packages/docs/src/pages/core-concepts/integrating-with-reach-ui.js
yarn.lock

simplifying the page, removed dialog example

Simplify page for using reach ui

---

packages/docs/src/pages/components/index.js

Fixes #72 
I built this page without considering multiple themes. Have changed the css to use either components (that adapt to theme) or use theme tokens like 'App.borderColor'

Components page: Make theme agnostic design

---

packages/docs/src/App.js
packages/docs/src/pages/components/alert.js
packages/docs/src/pages/components/index.js
packages/docs/src/pages/index.js
packages/react-ui/index.js
packages/react-ui/package.json
packages/react-ui/src/components/alert/alert.styles.js
packages/react-ui/src/components/alert/index.js
packages/react-ui/src/components/button/index.js
packages/react-ui/src/themes/base.js
packages/react-ui/src/themes/dark.js
packages/react-ui/src/themes/light.js
yarn.lock

Alert component

---

packages/react-ui/src/components/stack/index.js
packages/react-ui/src/primitives/interpolate.js

Something to think about again later

Fix: remove warning about margin end

---

packages/docs/src/App.js
packages/docs/src/components/page.js
packages/docs/src/pages/components/index.js
packages/docs/src/pages/components/tabs.js
packages/docs/src/pages/index.js
packages/react-ui/index.js
packages/react-ui/package.json
packages/react-ui/src/components/button/button.styles.js
packages/react-ui/src/components/tabs/index.js
packages/react-ui/src/components/tabs/tabs.styles.js
packages/react-ui/src/components/theme-provider/index.js
packages/react-ui/src/primitives/element.js
packages/react-ui/src/themes/base.js
packages/react-ui/src/themes/dark.js
packages/react-ui/src/themes/light.js
yarn.lock

Add tabs component

---

packages/react-ui/src/primitives/element.js

margin: 0 is ignored
```diff
- if (props[m]) margins[m] = props[m]
+ if (typeof themeStyles[m] !== 'undefined') margins[m] = themeStyles[m]
```

handle 0 for margin values

---

package.json
packages/visual-tests/.gitignore
packages/visual-tests/.storybook/main.js
packages/visual-tests/fonts.css
packages/visual-tests/generate-examples.js
packages/visual-tests/package.json
yarn.lock

Added a package that generates examples by parsing the source of documentation pages and then feeds them into storybook. These stories are used for visual tests with [chromatic](https://www.chromaticqa.com)

generated visual tests

---

packages/react-ui/src/components/form/form.styles.js
packages/react-ui/src/components/stack/index.js
packages/react-ui/src/themes/base.js
packages/react-ui/src/themes/dark.js
packages/react-ui/src/themes/light.js

Fix https://github.com/siddharthkp/react-ui/issues/40
Built on top of https://github.com/siddharthkp/react-ui/pull/80 + https://github.com/siddharthkp/react-ui/pull/81
Broke and fixed forms. Visual tests are green now 🎉

Fix specificity issues

---

packages/docs/package.json
packages/visual-tests/package.json

update version to fix tests + docs
